[package]
name = "ac-outpost"
version = "0.1.154"
authors = ["Kaku <obiekaku@gmail.com>"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer:0.12.10
"""

[dependencies]
cosmwasm-schema = "1.1.3"
cosmwasm-std = {version="1.1.3", default-features = false, features = ["stargate", "staking"]}
cosmwasm-storage = "1.1.3"
cw-storage-plus = "1.0.1"
cw2 = "1.0.1"
cw4-stake = "1.0.1"
schemars = "0.8.10"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.31" }
cosmos-sdk-proto = {version="0.17", default-features = false, features=["cosmwasm"]}
wyndex = {git = "https://github.com/wynddao/wynddex.git"}
wyndex-stake = {git = "https://github.com/wynddao/wynddex.git", features=["library"]}
wyndex-pair = {git = "https://github.com/wynddao/wynddex.git"}
wyndex-multi-hop = {git = "https://github.com/wynddao/wynddex.git", features=["library"]}
wyndex-pair-lsd = {git = "https://github.com/wynddao/wynddex.git", features=["library"]}

semver = "1"
cw20-stake = {git = "https://github.com/DA0-DA0/dao-contracts.git", features=["library"]}
cw20 = "1.0.1"
cw20-vesting = {git="https://github.com/wynddao/wynddao.git"}
wynd-stake = {git = "https://github.com/wynddao/wynddao.git", features=["library"]}

[dev-dependencies]
cw-multi-test = "0.16.2"
